import type { GetServerSideProps, NextPage } from "next";
import { useEffect, useContext } from "react";
import Head from "next/head";

const ProfilePage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>Logged In</p>
      </main>
    </div>
  );
};

export default ProfilePage;

// export const getServerSideProps: GetServerSideProps = async (context) => {
//   // export async function getServerSideProps(ctx: any) {
//   console.log("context", context.query);
//   const { code } = context.query;
//   //   const session = await getSession(ctx);
//   console.log(process.env.NEXT_PUBLIC_API_URL);

//   await fetch(`${process.env.NEXT_PUBLIC_API_URL}/auth/login`, {
//     method: "POST",
//     headers: {
//       "Content-Type": "application/json",
//     },
//     body: JSON.stringify({
//       code,
//       redirect_uri: process.env.NEXT_PUBLIC_CALLBACK_URL,
//     }),
//   })
//     .then((res) => res.json())
//     .then(({ discord_user, eden_user, token }) => {
//       console.log({ discord_user, eden_user, token });
//       //   localStorage.setItem("eden_token", token);
//       //   return { discord_user, eden_user, token };
//     });

//   return {
//     props: {},
//   };
// };
