import type { NextPage } from "next";
import { useEffect, useState, useMemo } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const API_URL = "http://localhost:5001";
const CALLBACK_URL = "http://localhost:3000/callback";

const Home: NextPage = () => {
  // useEffect(() => {
  //   console.log("Hello from useEffect");
  //   const fetcher = async () => {
  //     const res = await fetch("/api/hello");
  //     const data = await res.json();
  //     console.log(data);
  //   };
  //   fetcher();
  // }, []);

  const [loginUrl, setLoginUrl] = useState("");
  let queryParams = useMemo(() => {
    return new URLSearchParams();
  }, []);
  queryParams.append("redirect_uri", CALLBACK_URL as string);

  useEffect(() => {
    fetch(`${API_URL}/auth/init?` + queryParams.toString())
      .then((res) => res.json())
      .then((data) => {
        console.log(data);
        let { loginUrl } = data;
        setLoginUrl(loginUrl);
      });
  }, [queryParams]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>{loginUrl}</p>
        <a className="App-link" href={loginUrl}>
          Login with Discord
        </a>
      </main>
    </div>
  );
};

export default Home;
